server:
  port: 8080
spring:
    application:
      name: backend
    datasource:
      url: jdbc:mysql://localhost:3306/toeic
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
